# Generated by Django 5.1.4 on 2024-12-10 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0005_alter_emprestimo_leitor_alter_emprestimo_livro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leitor',
            name='data_nascimento',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='leitor',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
