# Generated by Django 5.1.4 on 2024-12-10 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0006_alter_leitor_data_nascimento_alter_leitor_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editora',
            name='endereco',
            field=models.CharField(max_length=200),
        ),
    ]
